name: dr_chong_poultry
description: "DrChongPoultry Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  font_awesome_flutter: ^11.0.0
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#0175c2"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png