// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDhGmEvCnopM2eLJLcbY1RiIuof4obsQ8',
    appId: '1:981927544561:web:270150800246ab14790b50',
    messagingSenderId: '981927544561',
    projectId: 'drchongpoultry',
    authDomain: 'drchongpoultry.firebaseapp.com',
    storageBucket: 'drchongpoultry.firebasestorage.app',
    measurementId: 'G-7TGTZZGJR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJ-XHo82_idfxUz7FrYdZi2VewIUMrIE',
    appId: '1:981927544561:android:f6f5382743982da4790b50',
    messagingSenderId: '981927544561',
    projectId: 'drchongpoultry',
    storageBucket: 'drchongpoultry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAyRLgN-o7QXPAa3YRJ_iLZYDmknJRjWE',
    appId: '1:981927544561:ios:9d42abe7f95983a1790b50',
    messagingSenderId: '981927544561',
    projectId: 'drchongpoultry',
    storageBucket: 'drchongpoultry.firebasestorage.app',
    iosBundleId: 'com.example.medicineApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAyRLgN-o7QXPAa3YRJ_iLZYDmknJRjWE',
    appId: '1:981927544561:ios:9d42abe7f95983a1790b50',
    messagingSenderId: '981927544561',
    projectId: 'drchongpoultry',
    storageBucket: 'drchongpoultry.firebasestorage.app',
    iosBundleId: 'com.example.medicineApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDhGmEvCnopM2eLJLcbY1RiIuof4obsQ8',
    appId: '1:981927544561:web:3e0a9c8693d821cd790b50',
    messagingSenderId: '981927544561',
    projectId: 'drchongpoultry',
    authDomain: 'drchongpoultry.firebaseapp.com',
    storageBucket: 'drchongpoultry.firebasestorage.app',
    measurementId: 'G-KEYBQM9G90',
  );
}
